// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exfduwwkneyxfododmhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4ZmR1d3drbmV5eGZvZG9kbWhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzQ4NjEsImV4cCI6MjA2NDQ1MDg2MX0.BGL-F6DowvaCULTMgynYtZ-OmQTDh-Fn2e3reTuZV7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});